import {
  AccountBalanceWalletOutlined,
  DashboardOutlined,
  ErrorOutline,
  HelpOutline,
  HistoryOutlined,
  Inventory2Outlined,
  LockOutlined,
  PointOfSaleOutlined,
  ReceiptLongOutlined,
  SettingsOutlined,
  StorefrontOutlined,
  ShoppingBagOutlined,
  GroupsOutlined,
  DescriptionOutlined,
  InboxOutlined,
  SupportOutlined,
} from "@mui/icons-material";
import type { InventoryProduct, NavItem } from "./types";

export const navItems: NavItem[] = [
  { label: "Dashboard", icon: "./chart-pie.jpg" },
  {
    label: "Inventory",
    icon: ShoppingBagOutlined,
    active: true,
    children: ["My inventory", "Purchase", "Inventory adjustment"],
  },
  {
    label: "Online store",
    icon: ShoppingBagOutlined,
    active: true,
    children: ["Online Orders", "Settlement & payout", "Order history"],
  },
  { label: "POS & Billing", icon: "./file-lines.jpg" },
  { label: "Discrepancies", icon: "./inbox-full.jpg", badge: "4" },
  { label: "Transaction History", icon: GroupsOutlined },
];

export const utilityNavItems: NavItem[] = [
  { label: "Help", icon: "./life-saver.png" },
  { label: "Settings", icon: "./book.jpg" },
];

export const products: InventoryProduct[] = [
  {
    id: "pears",
    name: "Pears",
    subtitle: "Original Soap",
    category: "Namkeen",
    hsn: "19023010",
    gst: "18%",
    label: "Packaged Item",
    labelTone: "orange",
    totalQuantity: "650",
    rows: [
      {
        id: "pears-1",
        upc: "1234567890",
        batch: "-",
        price: "₹20,000",
        weight: "200g Pack of 3",
        offlinePrice: "₹200",
        quantity: "800",
        channel: "Offline",
        actionLabel: "Added by you",
        approvalPending: true,
      },
      {
        id: "pears-2",
        upc: "1234567890",
        batch: "1",
        price: "₹20,000",
        weight: "200g",
        offlinePrice: "₹200",
        quantity: "800",
        channel: "Offline",
        actionLabel: "Added by you",
        approvalPending: true,
      },
      {
        id: "pears-3",
        batch: "2",
        price: "₹20,000",
        weight: "200g",
        offlinePrice: "₹200",
        quantity: "800",
        channel: "",
      },
      {
        id: "pears-4",
        batch: "3",
        price: "₹20,000",
        weight: "200g",
        offlinePrice: "₹200",
        quantity: "800",
        channel: "",
      },
      {
        id: "pears-5",
        upc: "1234567890",
        batch: "-",
        price: "₹20,000",
        weight: "200g",
        offlinePrice: "₹200",
        quantity: "800",
        channel: "Offline",
        npc: true,
      },
      {
        id: "pears-6",
        upc: "1234567890",
        batch: "-",
        price: "₹20,000",
        weight: "200g",
        offlinePrice: "₹200",
        quantity: "800",
        channel: "Offline",
        npc: true,
      },
    ],
  },
  {
    id: "basmati",
    name: "Basmati Rice",
    hsn: "19023010",
    gst: "18%",
    label: "Loose Item",
    labelTone: "blue",
    totalQuantity: "650kg",
    barcodeAction: true,
    rows: [
      {
        id: "rice-1",
        upc: "1234567890",
        batch: "-",
        offlinePrice: "₹200",
        quantity: "800",
        channel: "Offline",
        actionLabel: "Added by you",
      },
      {
        id: "rice-2",
        upc: "1234567890",
        batch: "1",
        offlinePrice: "₹200",
        quantity: "800",
        channel: "Offline",
        actionLabel: "Added by you",
      },
      {
        id: "rice-3",
        batch: "2",
        offlinePrice: "₹200",
        quantity: "800",
        channel: "",
      },
      {
        id: "rice-4",
        batch: "3",
        offlinePrice: "₹200",
        quantity: "800",
        channel: "",
      },
      {
        id: "rice-5",
        batch: "-",
        offlinePrice: "₹200",
        quantity: "800",
        channel: "Offline",
      },
    ],
  },
];

export const quickStats = [
  { label: "Inventory value", value: "₹22.8L", icon: Inventory2Outlined },
  { label: "Online orders", value: "124", icon: StorefrontOutlined },
  {
    label: "Payout pending",
    value: "₹48K",
    icon: AccountBalanceWalletOutlined,
  },
  { label: "Invoices", value: "88", icon: ReceiptLongOutlined },
];
